version: "3.9"

services:
  app:
    build: .
    container_name: backend
    environment:
      PGHOST: 'db'
      PGDATABASE: 'db'
      PGUSER: 'postgres'
      PGPASSWORD: 'postgres'
    volumes:
      - .:/go/src/
    networks:
      - postgres
    depends_on:
      - db

  db:
    image: postgres:14.1
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    networks:
      - postgres
    volumes: 
      - db:/var/lib/postgresql/data

networks:
  postgres:
    driver: bridge

volumes:
  db:
    driver: local
