version: "3.9"

services:
  app:
    build: .
    container_name: backend
    environment:
      - DB_URL=postgres://postgres:4MQnuzi.VPFrA6khB_PA@superbrunfo.csv0eo4pkrvl.sa-east-1.rds.amazonaws.com:5432/superbrunfo
    volumes:
      - .:/go/src/
    networks:
      - postgres
    depends_on:
      - db
    expose:
      - 8080
      # - db-stg

  db:
    image: postgres:14.1
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    networks:
      - postgres
    volumes: 
      - db:/var/lib/postgresql/data

  # db-stg:
  #   image: postgres:14.1
  #   restart: always
  #   container_name: db-stg
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: db
  #     PGDATA: /var/lib/postgresql/data/pgdata-stg
  #   ports:
  #     - '5433:5432'
  #   networks:
  #     - postgres
  #   volumes: 
  #     - db:/var/lib/postgresql/data

networks:
  postgres:
    driver: bridge

volumes:
  db:
    driver: local
