DROP TYPE IF EXISTS attribute;

DROP TABLE IF EXISTS "round";
DROP TABLE IF EXISTS match;
DROP TABLE IF EXISTS card_in_deck;
DROP TABLE IF EXISTS deck;
DROP TABLE IF EXISTS "card";

CREATE EXTENSION IF EXISTS "uuid-ossp";
