version: "3.9"

services:
  app:
    build: .
    container_name: backend
    environment:
      - DB_URL=postgres://postgres:postgres@localhost:5432/postgres
    volumes:
      - .:/go/src/
    networks:
      - postgres
    depends_on:
      - db
      - redis
    expose:
      - 8080

  db:
    image: postgres:14.1
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - '5432:5432'
    networks:
      - postgres
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data

networks:
  postgres:
    driver: bridge

volumes:
  db:
    driver: local
  redis:
    driver: local
