name: ci-workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      name: dev
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: 5432
      DB_NAME: superbrunfo
      DB_URL: ${{ secrets.DB_URL }}
      AWS_INSTANCE_SG_ID: sg-0a6f55c2bf1c6081e
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: get runner ip address
        id: ip
        uses: haythem/public-ip@v1.2
      - name: whitelist runner ip address
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 5432 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Create .env file
        run: echo "${{secrets.ENV_FILE }}" > backend/internal/infra/database/.env |
             echo "${{secrets.ENV_FILE }}" > backend/internal/service/.env
      
      - name: Run tests
        run: cd backend && go test -v ./...

      - name: revoke runner ip address
        run: |
          aws ec2 revoke-security-group-ingress \
            --group-id $AWS_INSTANCE_SG_ID \
            --protocol tcp \
            --port 5432 \
            --cidr ${{ steps.ip.outputs.ipv4 }}/32

#   deploy-stg:
#     runs-on: ubuntu-latest
#     env:
#       name: stg
#     needs: deploy-dev
#     steps:
#       - name: 'Create .env file'
#         run: |
#           touch backend/internal/infra/database/.env |
#           touch backend/internal/service/.env
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           go-version: 1.19
#       - run: cd backend && go test -v ./...

#   deploy-prd:
#     runs-on: ubuntu-latest
#     env:
#       name: prd
#     needs: deploy-stg
#     steps:
#       - name: 'Create .env file'
#         run: |
#           touch backend/internal/infra/database/.env |
#           touch backend/internal/service/.env
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           go-version: 1.19
#       - run: cd backend && go test -v ./...
