name: ci-workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      name: dev
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: 5432
      DB_NAME: superbrunfo
      DB_URL: ${{ secrets.DB_URL }}
    steps:
      - name: Get Github action IP
        id: ip
        uses: haythem/public-ip@v1.2
      - name: Setting environment variables..
        run: |
          echo "AWS_DEFAULT_REGION=sa-east-1" >> $GITHUB_ENV
          echo "AWS_SG_NAME=default" >> $GITHUB_ENV
          
      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32    
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run docker-compose
        run: cd backend && docker-compose up -d

      - name: Create .env file
        run: echo "${{secrets.ENV_FILE }}" > backend/game/infra/database/.env |
             echo "${{secrets.ENV_FILE }}" > backend/game/usecases/.env
      
      - name: Run tests
        run: cd backend && go test -v ./...

      - name: Remove Github Actions IP from security group
        run: |
          aws ec2 revoke-security-group-ingress --group-name ${{ env.AWS_SG_NAME }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ env.AWS_DEFAULT_REGION }}
        if: always()

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cidstein/super-brunfo:latest

#   deploy-stg:
#     runs-on: ubuntu-latest
#     env:
#       name: stg
#     needs: deploy-dev
#     steps:
#       - name: 'Create .env file'
#         run: |
#           touch backend/game/infra/database/.env |
#           touch backend/game/usecases/.env
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           go-version: 1.19
#       - run: cd backend && go test -v ./...

#   deploy-prd:
#     runs-on: ubuntu-latest
#     env:
#       name: prd
#     needs: deploy-stg
#     steps:
#       - name: 'Create .env file'
#         run: |
#           touch backend/game/infra/database/.env |
#           touch backend/game/usecases/.env
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           go-version: 1.19
#       - run: cd backend && go test -v ./...
