name: ci-workflow

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    env:
      name: dev
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: 5432
      DB_NAME: superbrunfo
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - run: |
          echo $DB_USER |
          echo $DB_HOST
      - run: echo "${{secrets.ENV_FILE }}" > backend/game/infra/database/.env
      - run: echo "${{secrets.ENV_FILE }}" > backend/game/usecases/.env
      - run: cd backend && go test -v ./...

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: cidstein/super-brunfo:latest

#   deploy-stg:
#     runs-on: ubuntu-latest
#     env:
#       name: stg
#     needs: deploy-dev
#     steps:
#       - name: 'Create .env file'
#         run: |
#           touch backend/game/infra/database/.env |
#           touch backend/game/usecases/.env
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           go-version: 1.19
#       - run: cd backend && go test -v ./...

#   deploy-prd:
#     runs-on: ubuntu-latest
#     env:
#       name: prd
#     needs: deploy-stg
#     steps:
#       - name: 'Create .env file'
#         run: |
#           touch backend/game/infra/database/.env |
#           touch backend/game/usecases/.env
#       - uses: actions/checkout@v2
#       - uses: actions/setup-go@v2
#         with:
#           go-version: 1.19
#       - run: cd backend && go test -v ./...
